apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: 'ci-tech-selector'
description: 'Parse Config File'

inputs:
  TECH:
    description: 'asdf'
  MVN-COMPILE-ARGS:
    description: 'asdf'
  MVN-TEST-ARGS:
    description: 'asdf'
  PY-REQUIREMENTS:
    description: 'asdf'
  PY-TEST-ARGS:
    description: 'asdf'

runs:
  using: composite
  steps:
    - name: CI - Maven3.9
      if: ${{ inputs.TECH == 'maven3.9' }}
      id: ci-maven
      kind: build
      uses: sbatchelder-cba/ci-maven-3.9@v0.0.3
      with:
        mvn-compile-args: ${{ inputs.MVN-COMPILE-ARGS }}
        mvn-test-args: ${{ inputs.MVN-TEST-ARGS }}


    - name: CI - Python
      if: ${{ inputs.TECH == 'python3.10' }}
      id: ci-python
      kind: build
      uses: sbatchelder-cba/ci-python-3.10@v0.0.4
      with:
        py-test-args: ${{ inputs.PY-TEST-ARGS }}
        py-requirements: ${{ inputs.PY-REQUIREMENTS }}